# Generated by Django 4.2.13 on 2024-06-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryimage_caption_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-caption_updated_on']},
        ),
    ]
