# Generated by Django 4.2.13 on 2024-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('wheelchair_access', models.CharField()),
            ],
        ),
    ]
