# Generated by Django 4.2.13 on 2024-06-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='wheelchair_access',
            field=models.CharField(choices=[('Wheelchair Lanes Available', 'Wheelchair Lanes Available'), ('No Wheelchair Lanes', 'No Wheelchair Lanes')]),
        ),
    ]
