# Generated by Django 4.2.13 on 2024-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_network_wheelchair_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='wheelchair_access',
            field=models.CharField(choices=[('Wheelchair Sheets Available', 'Wheelchair Sheets Available'), ('No Wheelchair Sheets', 'No Wheelchair Sheets')]),
        ),
    ]
