# Generated by Django 4.2.13 on 2024-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_network_wheelchair_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='wheelchair_access',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=150),
        ),
    ]
