# Generated by Django 4.2.13 on 2024-05-31 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('Sheet 1 at 18.00 - 19.30', 'Sheet 1 at 18.00 - 19.30'), ('Sheet 2 at 18.00 - 19.30', 'Sheet 2 at 18.00 - 19.30'), ('Sheet 3 at 18.00 - 19.30', 'Sheet 3 at 18.00 - 19.30'), ('Sheet 1 at 20.00 - 21.30', 'Sheet 1 at 20.00 - 21.30'), ('Sheet 2 at 20.00 - 21.30', 'Sheet 2 at 20.00 - 21.30'), ('Sheet 3 at 20.00 - 21.30', 'Sheet 3 at 20.00 - 21.30')])),
                ('wheelchair_lane', models.CharField(choices=[('Not Required', 'Not Required'), ('Required', 'Required')])),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TBC+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
