# Generated by Django 4.2.13 on 2024-06-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='wheelchair_lane',
            new_name='wheelchair_sheet',
        ),
    ]
