# Generated by Django 4.2.13 on 2024-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_wheelchair_lane_booking_wheelchair_sheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='session',
            new_name='sheet_time',
        ),
    ]
