# Generated by Django 4.2.13 on 2024-06-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_session_booking_sheet_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
    ]
