# Generated by Django 4.2.13 on 2024-06-20 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sheet_time',
            field=models.CharField(choices=[('Sheet 1 at 18.00 - 19.30', 'Sheet 1 at 18.00 - 19.30'), ('Sheet 2 at 18.00 - 19.30', 'Sheet 2 at 18.00 - 19.30'), ('Sheet 3 at 18.00 - 19.30', 'Sheet 3 at 18.00 - 19.30'), ('Sheet 1 at 20.00 - 21.30', 'Sheet 1 at 20.00 - 21.30'), ('Sheet 2 at 20.00 - 21.30', 'Sheet 2 at 20.00 - 21.30'), ('Sheet 3 at 20.00 - 21.30', 'Sheet 3 at 20.00 - 21.30')], max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wheelchair_sheet',
            field=models.CharField(choices=[('Not Required', 'Not Required'), ('Required', 'Required')], max_length=150),
        ),
    ]
